name: Build Nocturne Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            docker-compose \
            wget \
            unzip \
            genimage \
            pigz \
            binfmt-support

      - name: Enable QEMU multi-architecture
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build kernel
        run: |
          cd resources/kernel
          docker compose build
          docker compose run --rm build

      - name: Build image
        run: |
          cd resources
          # 设置环境变量
          export NOCTURNE_IMAGE_VERSION="v3.0.0-beta2"
          export NOCTURNE_UI_TAG="v3.0.0-beta2"
          export NOCTURNED_TAG="v1.0.6"
          export NOCTURNE_UBOOT_TOOL_TAG="v1.0.2"
          export NOCTURNE_UBOOT_TAG="v2025.04-nocturne1"
          export ALPINE_BRANCH="v3.21"
          export ALPINE_MIRROR="https://dl-cdn.alpinelinux.org/alpine"
          export DEFAULT_TIMEZONE="Etc/UTC"
          export DEFAULT_HOSTNAME="nocturne"
          export DEFAULT_ROOT_PASSWORD="nocturne"
          export DEFAULT_DROPBEAR_ENABLED="true"
          export DEFAULT_SERVICES="hostname local modules networking ntpd syslog"
          export SYSINIT_SERVICES="rngd"
          export BOOT_SERVICES="swap"
          export SIZE_ROOT_FS="1280M"
          export SIZE_DATA="990M"
          export OUTPUT_PATH="/output"
          export CACHE_PATH="/cache"
          export STAGES="00 10 20 30 40 50"
          export WORK_PATH="/work"
          export IMAGE_PATH="${WORK_PATH}/img"
          export RES_PATH=/resources/
          export DEF_STAGE_PATH="${RES_PATH}/scripts/stages"
          export ROOTFS_PATH="${WORK_PATH}/root_fs"
          export DATAFS_PATH="${WORK_PATH}/data_fs"
          # 执行构建脚本
          ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2  # 尝试使用 v4.6.2 版本
        with:
          name: nocturne-firmware
          path: /output
